Remove data versions from the Bukkit adapters
EngineHub/WorldEdit pull request #1507
Opened 2020-08-30 06:42 UTC by me4502

Adapters PR: https://github.com/EngineHub/worldedit-adapters/pull/20

There's API to handle this that exists from 1.13.2 onwards, so no need to have it in the adapters.

2020-08-30 16:46 UTC, wizjany commented
One notable downside of this is that schematics will be saved with a valid DV even if the data in them lacks properties due to missing adapters. This causes DFU issues later when loading them in an updated WE.

2020-08-31 00:17 UTC, me4502 commented
I somewhat feel having a valid DV is better than having an invalid one. Technically the blocks are all still valid, they just refer to the default state at that DV

2020-09-06 20:48 UTC, octylFractal requested changes
Personally I would like for this to change it so that schematics _cannot_ be saved if no adapter exists, at least not without a configuration option change to confirm they know what they are doing. It's way too common for users to simply not know that the copy does not have all the data it needs.

2020-09-18 11:49 UTC, me4502 commented
This PR now prevents schematics from being saved when the dataversion is -1, and sets the dataversion to -1 when an adapter is not found.

This is done at the command level, to prevent issues from occurring on the API side.

2020-09-18 20:52 UTC, octylFractal requested changes

2020-09-18 20:52 UTC, octylFractal commented on worldedit-core/src/main/resources/lang/strings.json
> +    "worldedit.schematic.unsupported-minecraft-version": "This version of WorldEdit does not support your Minecraft version. Schematics will not work until this is resolved. Update WorldEdit to resto
Unsure if `Update WorldEdit to restore this functionality.` is the correct wording here, in a potential future where we cut out e.g. 1.13.2 support, _updating_ will do nothing to fix this issue. A bit niche, but I'd like to have consistent messaging. Perhaps just dropping the last line is sufficient?

2020-09-19 07:46 UTC, octylFractal approved these changes

2020-09-19 08:00 UTC, merged