Workaround for snapshot files with not-to-spec slashes.
EngineHub/WorldEdit pull request #1508
Opened 2020-08-30 16:36 UTC by wizjany

Some utilities will create zip entries using windows path separators, which despite being against the zip file specification, we should probably read in anyway.

2020-09-02 12:45 UTC, me4502 approved these changes

2020-09-03 15:48 UTC, wizjany commented on worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ZippedMcRegionChunkStore.java
> +                if (entryName.startsWith(worldName + "/")) {
on second look this line is still broken, it doesn't use the matcher like the TrueZip version does.

2020-09-12 00:41 UTC, octylFractal requested changes

2020-09-12 00:41 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ZippedMcRegionChunkStore.java
> +                            endIndex = entryName.indexOf('\\');
Shouldn't this be `lastIndexOf`?

2020-09-12 01:12 UTC, merged