Use block change limit for //copy
EngineHub/WorldEdit pull request #1536
Opened 2020-09-21 10:12 UTC by me4502

Fixes #979

2020-09-21 18:22 UTC, wizjany commented
This is a super hacky and inaccurate workaround :\
On one hand, we can't exactly add checked exceptions to InputExtent now, but I don't know if this is the correct solution honestly.

2020-09-26 02:05 UTC, me4502 commented
I do agree, I just feel not allowing people to allocate giant chunks of memory when limits are in place may be worthwhile adding a hacky solution for

2020-09-27 04:39 UTC, octylFractal requested changes

2020-09-27 04:39 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
> +        Region clipboardBounds = region instanceof CuboidRegion
Can you make this a method on `Region`:
```java
default CuboidRegion getBoundingBox() {
    return new CuboidRegion(getMinimumPoint(), getMaximumPoint());
}
```
and just override in `CuboidRegion`? I feel like this is generically useful.

2020-09-27 04:39 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
> +            throw new MaxChangedBlocksException(session.getBlockChangeLimit());
```suggestion
        int limit = session.getBlockChangeLimit();
        if (clipboardBounds.getVolume() > limit) {
            throw new MaxChangedBlocksException(limit);
```

2020-09-27 05:39 UTC, octylFractal requested changes

2020-09-27 05:39 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
> +     * Get the bounding box of this region as a CuboidRegion.
```suggestion
     * Get the bounding box of this region as a {@link CuboidRegion}.
```

2020-09-27 05:40 UTC, octylFractal approved these changes

2020-09-27 05:40 UTC, merged