Add ^x,y,z relative offset support to the offset parser
EngineHub/WorldEdit pull request #1545
Opened 2020-10-02 11:21 UTC by me4502

Adds a `^` prefix to the offset parser that signifies the vector is a `forwards,up,left` offset rather than raw x/y/z
 
Fixes https://github.com/EngineHub/WorldEdit/issues/1442

2020-10-03 13:12 UTC, wizjany commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/OffsetConverter.java
> +        if (input.startsWith("^") && context.injectedValue(Key.of(Player.class)).isPresent()) {
any reason we require `Player` here? would any `Locatable` sender do? (even tho commandblocks' pitch/yaw are probably always `0,0` in theory mobs can be commandsenders too though we don't support them yet)

2020-10-09 02:01 UTC, octylFractal requested changes

2020-10-09 02:01 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/OffsetConverter.java
> +            );
Extract to a method.

2020-10-09 02:01 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/math/MathUtils.java
> +                case 270:
Revert these changes.

2020-10-09 19:19 UTC, octylFractal requested changes

2020-10-09 19:19 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/OffsetConverter.java
> +                .orElseThrow(() -> new IllegalStateException("An actor is required to use relative offsets"));
oh yea, you're uh, not supposed to throw here. Return a `FailedConversion.from(ex)` instead, or just wrap the whole thing in a `try-catch` :P

2020-10-10 05:42 UTC, octylFractal approved these changes

2020-10-10 05:49 UTC, merged