Add -w flag to butcher for water mobs
EngineHub/WorldEdit pull request #1548
Opened 2020-10-03 12:46 UTC by lewisjb

Fixes #1294

I couldn't seem to find support for this in Sponge - so just disabled it

2020-10-03 12:58 UTC, me4502 approved these changes

2020-10-03 12:59 UTC, wizjany commented on worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongeEntityProperties.java
> +        return false;  // Sponge doesn't support this
maybe just mark as // TODO for whenever api8 stuff is ready

2020-10-03 18:07 UTC, octylFractal requested changes

2020-10-03 18:07 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
> +                             @Switch(name = 'w', desc = "Also destroy water mobs")
IMO this should be `Also kill water mobs`, shouldn't it? "destroy" is just because armor stands are the only non-living creature.

2020-10-03 18:07 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
> +                       @Switch(name = 'w', desc = "Also destroy water mobs")
See other destroy comment.

2020-10-05 03:50 UTC, me4502 commented
Thanks

2020-10-05 03:50 UTC, merged