Add erosion brush
EngineHub/WorldEdit pull request #1559
Opened 2020-10-11 03:32 UTC by lewisjb

Implements the erode brush specified in #1288

2021-01-21 09:32 UTC, me4502 approved these changes

2021-01-24 02:55 UTC, wizjany commented
discussion from discord: https://i.imgur.com/WaJtOmB.png
I was planning on doing this myself but I ended up doing WG stuff instead. Might get to it at some point again unless you or someone else wants to do it.

2021-02-01 17:55 UTC, octylFractal requested changes
I'd like to officially mark this as needing the changes wiz suggested, as it sounds like a more useful and general tool.

2022-04-10 03:57 UTC, me4502 commented
Above suggestions have been applied in https://github.com/EngineHub/WorldEdit/pull/2078

2022-04-10 03:57 UTC, closed without merging