[WIP] Schematic Share system
EngineHub/WorldEdit pull request #1591
Opened 2020-11-24 10:37 UTC by me4502

This PR adds a command in game, that shares a schematic with a URL.

`/schem share`.

2020-11-24 16:44 UTC, kashike requested changes

2020-11-24 16:44 UTC, kashike commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
> +            return pasteService.paste(new String(Base64.getEncoder().encode(baos.toByteArray()), Charsets.UTF_8)).call();
```suggestion
            return pasteService.paste(new String(Base64.getEncoder().encode(baos.toByteArray()), StandardCharsets.UTF_8)).call();
```
No need to use Guava, the JDK has this.

2021-01-05 03:47 UTC, octylFractal requested changes

2021-01-05 03:47 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
> +        desc = "Save a schematic of your clipboard"
```suggestion
        desc = "Save your clipboard into a schematic file"
```

2021-01-05 03:47 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
> +        desc = "Share a schematic into your clipboard"
smh you corrected the `save` and then made the same mistake here
```suggestion
        desc = "Share your clipboard as a schematic online"
```

2021-01-05 03:47 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/util/paste/PasteMetadata.java
> +    public PasteMetadata() {
This is kinda pointless. Use the bits of syntax sugar Java gives you :P

2021-01-05 03:47 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
> +            Clipboard clipboard = holder.getClipboard();
Can we merge the saving code here and with `save` into a single method? DRY applies here, especially with how much custom logic is part of saving.

2021-01-05 06:01 UTC, octylFractal requested changes

2021-01-05 06:46 UTC, octylFractal approved these changes

2021-01-05 06:48 UTC, merged