Add instructions for unbinding tools/brushes on equip.
EngineHub/WorldEdit pull request #1595
Opened 2020-11-27 02:14 UTC by wizjany

Will hopefully cut down on this question.

2020-11-27 02:25 UTC, octylFractal requested changes

2020-11-27 02:25 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
> +                                                                   .clickEvent(ClickEvent.runCommand("/brush none"))
I think we prefer suggesting instead.

2020-11-27 02:25 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java
> +                                                                   .clickEvent(ClickEvent.runCommand("/tool none"))
Ditto here

2020-11-27 03:46 UTC, octylFractal approved these changes

2020-11-28 14:10 UTC, me4502 approved these changes

2020-11-28 14:13 UTC, merged