Add divide command
EngineHub/WorldEdit pull request #1928
Opened 2021-11-07 15:56 UTC by Lennart99

This PR adds a relatively simple yet useful command:
**//divide [number] [pattern]**.

This command performs a similar task to the existing **//center [pattern]** command, but gives the user more control by allowing the player to specify a division factor. This command would divide the selected region by the provided quantity and set those blocks to the provided pattern.

2021-11-07 19:51 UTC, wizjany requested changes
In the current implementation this is actually worse just //line with a hypothetical equal spaced pattern. It's unimplemented for anything beside cuboids, which means that it will always just place points from the lowest x,y,z in a line to the highest x,y,z. This means you don't even have control over which direction this "line" goes (like you do with the actual //line command). The division of the region is actually a division of this line - any other axes are ignored. Additionally the way rounding is done means this will create multiple overlapping 2x2 cubes if the "division factor" is relatively high compared to the length of the diagonal.

On that note, I feel like this would be a lot more useful as a grid command instead which truly subdivides the space in all axes, or better yet, a grid pattern that allows non-random repetition of sub-patterns. The syntax for doing this as a pattern in a 3d space might be a bit weird though.

2021-11-07 19:51 UTC, wizjany commented on worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
> +    List<Vector3> getDivisionPoints(int number);
this should have a `default` implementation or it's a breaking change

2021-11-07 19:51 UTC, wizjany commented on worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
> +     * Divides the region into N sections and returns a Set with all unique the points in between those sections.
this description is extremely misleading - it divides the *diagonal of the bounding box* and returns a *list* of points (which might only be unique in fractional parts).

2021-11-19 14:22 UTC, Lennart99 commented
I decided to re-write this feature and base the logic a bit more on the logic of //line. This simplified the logic and also optimized it quite a bit (it should be faster then //line now). This also means it won't generate 2x2 cubes anymore.
It however still is only implemented for cuboid regions, but it is now taking the correct positions (pos1 and 2 instead of min and max). I would like to also implement this for other region types, but I am not sure how this should work. 
Do you have any ideas?

2022-06-25 10:27 UTC, closed without merging