Add a check to the "levels" argument supplied for //asc and //desc
EngineHub/WorldEdit pull request #2085
Opened 2022-04-23 23:18 UTC by dordsor21

Feel free to commit separately with a different implementation, just keeping this the same as the quick FAWE patch. Can change downstream to whatever you guys implement as well.

2022-04-23 23:26 UTC, octylFractal requested changes
Minor styling fix, and would you mind extracting this to a common method so if it changes both places get updated?

2022-04-23 23:26 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/NavigationCommands.java
> +        checkArgument(levels >= 1 && levels <= (world.getMaxY() - world.getMinY()), "1 <= levels <= world height");
```suggestion
        checkArgument(1 <= levels && levels <= (world.getMaxY() - world.getMinY()), "1 <= levels <= world height");
```
This makes it look more like the error message, and I prefer to have bounds done this way.

2022-04-23 23:26 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/NavigationCommands.java
> +        checkArgument(levels >= 1 && levels <= (world.getMaxY() - world.getMinY()), "1 <= levels <= world height");
Ditto here.
```suggestion
        checkArgument(1 <= levels && levels <= (world.getMaxY() - world.getMinY()), "1 <= levels <= world height");
```

2022-04-24 15:30 UTC, closed without merging

2022-04-24 15:31 UTC, dordsor21 commented
For reference: IntellectualSites/FastAsyncWorldEdit#1718