Work around invalid legacy values in schematics
EngineHub/WorldEdit pull request #2171
Opened 2022-08-13 07:52 UTC by me4502

Not 100% happy about this; but currently a lot of legacy schematics include entirely broken blocks (Eg, `1:5` rather than `1:0`) because they used broken or poor quality world editing tools to alter the world. These are invalid post-1.13, but we can default to the default state for these blocks to at least recover _some_ of the data that was meant to be here, rather than skipping it entirely.

2022-08-28 07:37 UTC, octylFractal requested changes
Can we move this logic to the schematic loader itself?

2022-08-28 10:10 UTC, me4502 commented
@octylFractal Given these blocks are "equivalent", I feel the mapper is the right place to do it. Plus, I feel it'd be weird if the blocks work in the schem but not via other commands

2022-08-28 13:35 UTC, wizjany commented
imo they *shouldn't* be valid in other commands. `//set 1:5` is a typo or some other mistake. we should treat it as such and error to the user. the only reason this makes sense in the context of schems is because users can get schematics from dumb sources that have invalid data and there's no easy way to fix the schem itself.

2022-08-28 14:34 UTC, octylFractal commented
Yes, I agree with wiz here.

2022-08-29 14:08 UTC, octylFractal approved these changes

2022-08-29 14:08 UTC, merged