Schematic caching system for suggestions
EngineHub/WorldEdit pull request #2542
Opened 2024-06-01 04:33 UTC by me4502

This is a continuation of https://github.com/EngineHub/WorldEdit/pull/2212, as the PR is abandoned by its original author

2024-11-04 01:31 UTC, octylFractal requested changes

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
> +        return SAFE_FILENAME_REGEX.matcher(filename).matches();
This set of characters doesn't make sense, it's not safe for windows (contains `?`, `*`, doesn't ban COM and others), and POSIX will generally take anything. It also excludes extended Unicode characters for some reason, despite those being perfectly fine.

Can we just drop checking this aside from "you must have an extension", i.e. `^.+\..+$`?

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +    }
Let's not bother with the `Optional` path here. We're not currently dealing with non-default `Path` providers, and I don't expect to any time soon. Quote from the Javadocs of `newWatchService`:
> This exception is not thrown by FileSystems created by the default provider.

So, let's remove the `Optional` and just throw.

```suggestion
    public static RecursiveDirectoryWatcher create(Path root) throws IOException {
        WatchService watchService;
        try {
            watchService = root.getFileSystem().newWatchService();
        } catch (UnsupportedOperationException e) {
            throw new IllegalArgumentException("Root must support file watching", new RecursiveDirectoryWatcher(root, watchService));
        }
        return new RecursiveDirectoryWatcher(root, watchService);
    }
```

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/SchematicsManager.java
> +    }
Assuming that my `Optional`-removing suggestion is accepted, let's clean this up too:
```suggestion
    private void setupBackend() {
        try {
            backend = FileWatcherSchematicsBackend.create(schematicsDir);
        } catch (IOException e) {
            LOGGER.warn("Failed to initialize file-monitoring based schematics backend. Falling back to polling.", e);
            backend = PollingSchematicsBackend.create(schematicsDir);
        }
    }
```

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/SchematicsManager.java
> +            backend = new DummySchematicsBackend(); //fallback to dummy backend
This comment isn't needed. It's obvious.
```suggestion
            backend = new DummySchematicsBackend();
```

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/SchematicsManager.java
> +            schematicsDir = schematicsDir.toRealPath();
Let's not set this twice.
```suggestion
            Path schematicsDirByConfig = worldEdit.getWorkingDirectoryPath(worldEdit.getConfiguration().saveDir);
            Files.createDirectories(schematicsDirByConfig);
            schematicsDir = schematicsDirByConfig.toRealPath();
```

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/backends/DummySchematicsBackend.java
> +public class DummySchematicsBackend implements SchematicsBackend {
I feel like this backend should throw instead. We're using it as the driving force behind `//schem list` now, so if it fails, people shouldn't just get an empty list out, they should get an error. Or possibly, we shouldn't have this at all and should crash out if we have an error setting up.

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/backends/FileWatcherSchematicsBackend.java
> +    private final Set<Path> schematics = new HashSet<>();
Why are we not using a `Sets.newConcurrentHashSet()`? It would work much better since it doesn't need to lock the whole set.

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +        watchThread = new Thread(() -> {
Just in case, we should check for an existing `watchThread` and kill it or throw. Killing requires us to have a means of communicating to it.

2024-11-04 01:31 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +        watchThread.setName("RecursiveDirectoryWatcher");
At the very least we should identify ourselves fully. Perhaps we should also use a global counter.
```suggestion
        watchThread.setName("WorldEdit-RecursiveDirectoryWatcher");
```

2025-02-16 05:36 UTC, me4502 commented on worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
> +        return SAFE_FILENAME_REGEX.matcher(filename).matches();
So I do agree fundamentally here, although I feel like it'd make sense to do that separately to this change

2025-02-16 05:41 UTC, me4502 commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/schematic/backends/DummySchematicsBackend.java
> +public class DummySchematicsBackend implements SchematicsBackend {
So the current setup appears to be that it prints a warn in the console when it swaps out to this. IMO having it not completely explode is probably ideal, but still throwing an error makes sense. Would you be fine with me just swapping that log point to an error-level one?

2025-02-16 05:43 UTC, me4502 commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +        watchThread = new Thread(() -> {
So my memory of the Java thread model is a bit lacking; I feel like I've now set it up like that (it already appeared to be semi-setup for a Thread-interruption model), but not 100% sure

2025-02-16 06:44 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +            try {
Can we `interrupt()` here as well?

2025-02-16 06:44 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +            watchThread.interrupt();
We should `join` here first.

2025-02-16 06:45 UTC, octylFractal commented on worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RecursiveDirectoryWatcher.java
> +        watchThread = new Thread(() -> {
Yes, this should mostly be fine.

2025-02-16 07:03 UTC, octylFractal approved these changes

2025-02-16 07:25 UTC, merged